Repository blue-nebula/base, pull requests merged in 2020-07, with the labels that each got.

#95 Show chatting in radar
  src/game/capture.cpp
  src/game/defend.cpp
  src/game/game.h
  src/game/hud.cpp
Labels: enhancement

#80 Rework resolution options
  config/menus/options.cfg
Labels: enhancement, user interface

#79 Rework map selection menu
  config/menus/maps.cfg
Labels: enhancement, user interface

#99 Maps list improvements: better <random> and size display.
  config/menus/maps.cfg
Labels: enhancement, user interface

#105 Replace globs in CMake
  src/cmake/build_client.cmake
  src/cmake/build_genkey.cmake
  src/cmake/build_server.cmake
  src/xcode/main.m
Labels: bug, refactoring

#106 Do not remove the COMPLETE flag when setting existing aliases.
  src/engine/command.cpp
Labels: bug

#101 Refine Serverbrowser style
  config/menus/glue.cfg
  config/menus/servers.cfg
Labels: enhancement, user interface

#108 Add headers to CMake targets
  src/cmake/build_client.cmake
  src/cmake/build_genkey.cmake
  src/cmake/build_server.cmake
  src/scripts/trace-headers.py
Labels: bug

#118 Prevent crash in getvarfields when the ident doesn't exist.
  src/engine/command.cpp
Labels: bug, refactoring

#132 Add note in log when the server cannot load a requested map.
  src/game/server.cpp
Labels: enhancement

#110 Increase client/server update rate to 125Hz
  src/game/bomber.cpp
  src/game/capture.cpp
  src/game/client.cpp
  src/game/game.h
  src/game/server.cpp
Labels: discussion, enhancement

#127 Default indicatorminattack to 400.
  config/usage.cfg
  src/game/hud.cpp
Labels: enhancement

#135 Remove unterminated string in usage.cfg
  config/usage.cfg
Labels: bug
